CREATE TABLE weather_data (
 seq INT NOT NULL AUTO_INCREMENT,
 x INT,
 y INT,
 Date VARCHAR(8),
 Time INT,
 PTY INT,
 REH INT,
 RN1 INT,
 T1H FLOAT,
 UUU FLOAT,
 VEC INT,
 VVV FLOAT,
 WSD FLOAT,
 PRIMARY KEY(seq),
 UNIQUE INDEX(x, y, Date, Time)
) CHARSET=utf8;